name: Test Workflow CI
on:
  workflow_dispatch:
  push:
    branches:
      - "**"

env:
  APP_PJ_PREFIX: "hdeg"
  PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
  PACKAGE_REPO_TOKEN: ${{ secrets.PACKAGE_REPO_TOKEN }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    name: Java Junit Testing
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      testsFound: ${{ steps.check_test_files.outputs.testsFound }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      - name: Test with Gradle
        continue-on-error: true
        run: |
          chmod +x gradlew
          ./gradlew clean test --continue

      - name: Check if test has been done
        id: check_test_files
        run: |
          test_count=$(find . -type f -path '**/build/test-results/test/*' -name '*.xml' | wc -l)
          if [ $test_count -eq 0 ]; then
            echo "## No test files found!" >> $GITHUB_STEP_SUMMARY
            echo -e "testsFound=false\n" >> "$GITHUB_OUTPUT"
          else
            echo "## $test_count test files found!" >> $GITHUB_STEP_SUMMARY
            echo -e "testsFound=true\n" >> "$GITHUB_OUTPUT"
          fi
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        if: ${{steps.check_test_files.outputs.testsFound == 'true' }}
        with:
          name: junit-test-results
          path: |
            ${{ github.workspace }}/**/build/test-results/test
            ${{ github.workspace }}/**/build/reports/tests/test
            ${{ github.workspace }}/**/build/test-results/TEST-*.xml
            ${{ github.workspace }}/**/build/jacoco*
          retention-days: 3

  report:
    name: Generate Junit Testing Report
    needs: test
    if: ${{needs.test.outputs.testsFound == 'true' }}
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JUnit test results
        uses: actions/download-artifact@v4
        with:
          name: junit-test-results

      - name: Test Report
        id: test_reporter
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: JUnit Testing Summary Report
          path: '**/TEST-*.xml'
          reporter: java-junit
          max-annotations: 50
          list-tests: failed
          list-suites: all
          only-summary: false

      - name: Test coverage report
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
         paths: |
           ${{ github.workspace }}/**/build/jacoco/test/*.xml
         token: ${{ secrets.GITHUB_TOKEN }}
         title: '# :lobster: JaCoCo Coverage Report'
         pass-emoji: ':green_circle:'
         fail-emoji: ':red_circle:'
         comment-type: 'summary'